name: Generate ASCII Artwork

on: push

jobs:
  ascii_job:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout Repo
        uses: actions/checkout@v4

      - name: Read file
        run: ls -ltra
      
      - name: Install Cowsay Program
        run: ./ascii-script.sh

